In [166]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
import sklearn
from sklearn.cluster import KMeans

from pandas import Series, DataFrame
from pylab import rcParams
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics 
from sklearn.metrics import classification_report

In [109]:

#X = df4.ix[:,(0,1,2,3,4,5,6,7)].values
#Y = df4.ix[:,8].values


In [178]:
df4 = pd.read_csv('meteo.csv')
#se suprime registro nulos ya que con la cantidad que queda se logra un buen entrenamiento
df4.dropna(inplace=True)
RT = pd.get_dummies(df4['RainToday'],drop_first=True)


RTO = pd.get_dummies(df4['RainTomorrow'],drop_first=True)
winDir = pd.get_dummies(df4['WindGustDir'],drop_first=True)
winDir9am = pd.get_dummies(df4['WindDir9am'],drop_first=True)
winDir3pm = pd.get_dummies(df4['WindDir3pm'],drop_first=True)
Location = pd.get_dummies(df4['Location'],drop_first=True)

df4.drop(['RainToday', 'RainTomorrow','WindGustDir','WindDir9am','WindDir3pm','Location'],axis=1,inplace=True)

df4 = pd.concat([df4,winDir9am,winDir3pm,winDir,RTO,Location],axis=1)
df4.rename(index=str,columns={"Yes":"RainTomorrow"})
df4 = pd.concat([df4,RT],axis=1)

#elimina la fecha ya que el dia exacto no es relevante y genera variables dummy no productivas 
#si se quisiera usar

df4.drop(['Date','RISK_MM'],axis=1,inplace=True)

In [168]:
X = df4.iloc[:,:87].values
y = df4.iloc[:,87].values

In [169]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state=25)
print(X_test)

[[ 7.9 13.5  0.  ...  0.   0.   0. ]
 [25.5 32.3  0.8 ...  0.   0.   0. ]
 [16.3 27.   0.  ...  0.   0.   0. ]
 ...
 [ 7.6 15.4  0.  ...  0.   0.   0. ]
 [ 1.  24.6  0.  ...  0.   0.   0. ]
 [ 1.7 14.5  0.  ...  0.   0.   0. ]]


In [170]:
LogReg = LogisticRegression()
LogReg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [171]:
print("coeficientes del modelo: "+str(LogReg.coef_))
print("intercept: "+str(LogReg.intercept_))

coeficientes del modelo: [[-9.07459156e-03 -4.51385137e-02  9.93553640e+00 -2.37332618e-02
   2.01388489e-03  1.18730127e-03  4.94616157e-03  1.56295831e-04
  -3.93094883e-03 -3.35317983e-04  3.20524430e-04 -1.10273473e-02
  -3.83666067e-02  3.59098854e-02  4.80613019e-03  5.39879338e-02
  -1.41316587e-01 -1.95782473e-01 -5.34601349e-02  6.52389981e-02
   6.56127658e-03  1.10488345e-02 -8.52244808e-02  7.49817879e-02
  -7.61599195e-02  8.94270463e-02  5.52537246e-02  1.70849535e-02
  -8.92585443e-03  1.63344247e-01  1.31164596e-01  1.04717539e-01
  -1.88823366e-01  2.27831590e-02  8.24721535e-02  2.23711136e-03
  -7.16896238e-02 -5.27136002e-02  2.17546379e-02  9.59988298e-02
   7.99804310e-02 -6.84314396e-02 -3.16990474e-02 -6.09273661e-03
  -1.39636660e-01  6.97292537e-02  1.24677951e-01  1.31955245e-01
  -8.25487421e-02  2.03069372e-02 -5.59687780e-02  1.65078834e-01
  -4.71397081e-03  8.12332794e-02 -1.13568908e-01 -5.36342569e-02
   2.62558154e-02  6.88168454e-02  1.78394322e-02 -

In [172]:
y_pred = LogReg.predict(X_test)
y_pred[32:45]

array([1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=uint8)

In [173]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
confusion_matrix

array([[13158,     0],
       [    0,  3768]])

In [174]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13158
           1       1.00      1.00      1.00      3768

   micro avg       1.00      1.00      1.00     16926
   macro avg       1.00      1.00      1.00     16926
weighted avg       1.00      1.00      1.00     16926



In [175]:
from sklearn import tree
#Entrenamiento
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
#Predicciones
y_pred = clf.predict(X_test)
#Evaluación del rendimiento del clasificador
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
#Print de la matriz de confusión
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

[[13158     0]
 [    0  3768]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13158
           1       1.00      1.00      1.00      3768

   micro avg       1.00      1.00      1.00     16926
   macro avg       1.00      1.00      1.00     16926
weighted avg       1.00      1.00      1.00     16926



In [ ]:
# las variables que son bueno predictores son si hoy llovio o no, la temperatura min y max el factor de nubes y la presion
